In [94]:
import pandas as pd

In [95]:
data = pd.read_csv("matches.csv")

In [96]:
data.head(2)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2008,Bangalore,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,NaN
1,2,2008,Chandigarh,2008-04-19,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Chennai Super Kings,33,0,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",MR Benson,SL Shastri,NaN

In [97]:
data.columns

Index(['id', 'season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [98]:
len(data)

577

In [99]:
data.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2008,Bangalore,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,NaN
1,2,2008,Chandigarh,2008-04-19,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Chennai Super Kings,33,0,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",MR Benson,SL Shastri,NaN
2,3,2008,Delhi,2008-04-19,Rajasthan Royals,Delhi Daredevils,Rajasthan Royals,bat,normal,0,Delhi Daredevils,0,9,MF Maharoof,Feroz Shah Kotla,Aleem Dar,GA Pratapkumar,NaN
3,4,2008,Mumbai,2008-04-20,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,normal,0,Royal Challengers Bangalore,0,5,MV Boucher,Wankhede Stadium,SJ Davis,DJ Harper,NaN
4,5,2008,Kolkata,2008-04-20,Deccan Chargers,Kolkata Knight Riders,Deccan Chargers,bat,normal,0,Kolkata Knight Riders,0,5,DJ Hussey,Eden Gardens,BF Bowden,K Hariharan,NaN

In [100]:
#data = data[['season','winner']].drop_duplicates('season',keep="last")

In [101]:
#print(data)

In [102]:
data[data['win_by_runs']>50][["team1","team2","win_by_runs"]]

                           team1                        team2  win_by_runs
0          Kolkata Knight Riders  Royal Challengers Bangalore          140
9                Kings XI Punjab               Mumbai Indians           66
41              Rajasthan Royals  Royal Challengers Bangalore           65
55              Rajasthan Royals             Delhi Daredevils          105
59   Royal Challengers Bangalore             Rajasthan Royals           75
62           Chennai Super Kings  Royal Challengers Bangalore           92
72                Mumbai Indians        Kolkata Knight Riders           92
84           Chennai Super Kings              Deccan Chargers           78
85              Rajasthan Royals              Kings XI Punjab           78
95               Deccan Chargers             Rajasthan Royals           53
122          Chennai Super Kings        Kolkata Knight Riders           55
123               Mumbai Indians             Delhi Daredevils           98
143             Delhi Daredevils             Rajasthan Royals           67
147               Mumbai Indians              Deccan Chargers           63
166               Mumbai Indians  Royal Challengers Bangalore           57
205              Deccan Chargers         Kochi Tuskers Kerala           55
220  Royal Challengers Bangalore              Kings XI Punjab           85
225          Chennai Super Kings             Rajasthan Royals           63
227              Kings XI Punjab               Mumbai Indians           76
236              Kings XI Punjab  Royal Challengers Bangalore          111
240              Deccan Chargers              Kings XI Punjab           82
247          Chennai Super Kings  Royal Challengers Bangalore           58
253          Chennai Super Kings              Deccan Chargers           74
266             Rajasthan Royals  Royal Challengers Bangalore           59
320          Chennai Super Kings             Delhi Daredevils           86
343             Rajasthan Royals               Mumbai Indians           87
344          Chennai Super Kings             Delhi Daredevils           86
351  Royal Challengers Bangalore                Pune Warriors          130
357               Mumbai Indians  Royal Challengers Bangalore           58
370               Mumbai Indians          Chennai Super Kings           60
374               Mumbai Indians        Kolkata Knight Riders           65
375          Chennai Super Kings          Sunrisers Hyderabad           77
405          Chennai Super Kings             Delhi Daredevils           93
406              Kings XI Punjab          Sunrisers Hyderabad           72
438             Rajasthan Royals             Delhi Daredevils           62
482          Chennai Super Kings              Kings XI Punjab           97
497  Royal Challengers Bangalore              Kings XI Punjab          138
514  Royal Challengers Bangalore             Rajasthan Royals           71
553          Sunrisers Hyderabad               Mumbai Indians           85
560  Royal Challengers Bangalore                Gujarat Lions          144
563               Mumbai Indians             Delhi Daredevils           80
566  Royal Challengers Bangalore              Kings XI Punjab           82

In [103]:
len(data)

577

In [108]:
#data.dropna(axis=1,inplace=True)
# row wise